# -*- coding: utf-8 -*-
"""Assignment1_PearlKaur_705.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuFlvc0fTXLIBVzS4bSegjEVqn9CLfIc

## Problem 1: Arithmetic Operations ( Using Functions )

Write a Python program that performs various arithmetic operations on two numbers entered by the user.

1. Take **two numbers as input from the user**.

2. Perform the following **arithmetic operations**:
   - Addition
   - Subtraction
   - Multiplication
   - Division

3. The program must **handle division by zero gracefully**.If the user attempts to divide by zero, the program should display an appropriate message instead of producing an error.

4. If you are familiar with the concept of **function definition in Python**, implement each operation using **separate functions**.

5. Each function should:
   - Take the necessary inputs as parameters
   - Perform the required operation
   - Return or display the result.
"""

def summ(n1,n2):
  sumi=n1+n2
  print(sumi)
def diff(n1,n2):
  dif=n1-n2
  print(dif)
def prod(n1,n2):
  pro=n1*n2
  print(pro)
def div(n1,n2):
  if n2!=0:
    divi=n1/n2
    print(divi)
  elif n2==0:
    print("Invalid division")

n1=int(input('Enter a number: '))
n2=int(input('Enter a number: '))
choice=int(input('Enter 1 for addition, 2 for subtraction, 3 for multiplication, 4 for division: '))

switch={
    1:summ,
    2:diff,
    3:prod,
    4:div
}
if choice in switch:
    switch[choice](n1,n2)
else:
    print("Invalid Choice")

"""## Problem 2: Set Operations (Using Functions)

Write a Python program that performs various **set operations** on sets entered by the user.
1. Take the elements of **two sets** from the user as input.

2. Perform the following **basic set operations**:
   - Union
   - Intersection
   - Set Difference
   - Symmetric Difference

3. If you are familiar with the concept of **function definition in Python**, implement each operation using **separate functions**.  

4. Each function should:
   - Accept the required sets as parameters
   - Perform the corresponding set operation
   - Return or display the result.

5. Extend the program to perform the following tasks:

      i.  Write a function to check whether one set is a **subset** of another set and whether it is a **superset**.

      ii. Ask the user to enter an element and check whether the element **exists in the given set**.

      iii. Write a function to compute and display the **number of elements** in the set.

      iv. Take a list of elements from the user and convert it into a **set** to remove duplicate values.

      iv. Write a function that generates the **power set** (set of all possible subsets) of a given set.
"""

s1=[]
s2=[]
n1=int(input('Enter no. of elements in n1: '))
n2=int(input('Enter no. of elements in n2: '))
for ele in range(n1):
  ele=int(input('Enter element: '))
  s1.append(ele)
for el in range(n2):
  el=int(input('Enter element: '))
  s2.append(el)
s1=set(s1)
s2=set(s2)
print(s1)
print(s2)
def union(s1,s2):
  print('Union: ',s1.union(s2))
def intersection(s1,s2):
  print('Intersection: ',s1.intersection(s2))
def difference(s1,s2):
  print('Difference: ',s1.difference(s2))
def symmetric_difference(s1,s2):
  print('Symmetric Difference: ',s1.symmetric_difference(s2))
union(s1,s2)
intersection(s1,s2)
difference(s1,s2)
symmetric_difference(s1,s2)
#subset & superset
def sub(s1,s2):
  print(s1.issubset(s2))
  print(s1.issuperset(s2))
sub(s1,s2)

s=[]
n1=int(input('Enter no. of elements in n1: '))
for ele in range(n1):
  ele=int(input('Enter element: '))
  s.append(ele)
s=set(s)
s3=int(input("Enter number to be searched: "))
if(s3 in s):
  print('Element found in set.')
else:
  print('Element not found.')
#list to set
l1=[]
n=int(input('Enter no. of elements: '))
for i in range(n):
  i=int(input('Enter the element: '))
  l1.append(i)
l2=set(l1)
print(l2)
#power set
def power_set(s):
    result = [[]]
    for ele in s:
        new_subsets = []
        for subset in result:
            new_subsets.append(subset + [ele])
        result = result + new_subsets
    return result
print(power_set(s))

"""## Problem 3: Area and Volume Calculator Using Switch Case

Write a Python program that calculates the **area or volume** of different geometric shapes based on the user's choice.
The program should use a **switch-case structure** to select the appropriate operation.
## Area Formulas

| Shape | Area Formula | Parameters |
|------|--------------|-----------|
| Circle | $A = \pi r^2$ | $r$ = radius |
| Rectangle | $A = l \times b$ | $l$ = length, $b$ = breadth |
| Triangle | $A = \frac{1}{2}bh$ | $b$ = base, $h$ = height |
| Square | $A = a^2$ | $a$ = side |
| Parallelogram | $A = b \times h$ | $b$ = base, $h$ = height |

---

## Volume Formulas

| Shape | Volume Formula | Parameters |
|------|----------------|-----------|
| Cube | $V = a^3$ | $a$ = side |
| Cuboid | $V = l \times b \times h$ | $l$ = length, $b$ = breadth, $h$ = height |
| Sphere | $V = \frac{4}{3}\pi r^3$ | $r$ = radius |
| Cylinder | $V = \pi r^2 h$ | $r$ = radius, $h$ = height |
| Cone | $V = \frac{1}{3}\pi r^2 h$ | $r$ = radius, $h$ = height |
### Menu Options

Display the following menu and allow the user to choose an option:

**Area Calculations**

- 1 → Area of Circle  
- 2 → Area of Rectangle  
- 3 → Area of Triangle  
- 4 → Area of Square  
- 5 → Area of Parallelogram  

**Volume Calculations**

- 6 → Volume of Cube  
- 7 → Volume of Cuboid  
- 8 → Volume of Sphere  
- 9 → Volume of Cylinder  
- 10 → Volume of Cone

2. Take the **user's choice as input**.

3. Based on the selected option, ask the user to input the **required parameters** such as radius, length, breadth, height, or side.

4. Use a **switch-case structure** to perform the required calculation.

5. Display the **computed area or volume**.

"""

import math
def ar_circle():
  r=int(input('Enter radius: '))
  area=math.pi*r*r
  print('Area of circle: ',area)
def ar_rect():
  l=int(input('Enter length: '))
  b=int(input('Enter breadth: '))
  area=l*b
  print('Area of rectangle: ',area)
def ar_tri():
  b=int(input('Enter base: '))
  h=int(input('Enter height: '))
  area=0.5*b*h
  print('Area of triangle: ',area)
def ar_sq():
  a=int(input('Enter side: '))
  area=a*a
  print('Area of square: ',area)
def ar_para():
  b=int(input('Enter base: '))
  h=int(input('Enter height: '))
  area=b*h
  print('Area of parallelogram: ',area)
def cube():
  a=int(input('Enter side: '))
  volume=a*a*a
  print('Volume of cube: ',volume)
def cuboid():
  l=int(input('Enter length: '))
  b=int(input('Enter breadth: '))
  h=int(input('Enter height: '))
  volume=l*b*h
  print('Volume of cuboid: ',volume)
def sphere():
  r=int(input('Enter radius: '))
  volume=(4/3)*math.pi*r*r*r
  print('Volume of sphere: ',volume)
def cylinder():
  r=int(input('Enter radius: '))
  h=int(input('Enter height: '))
  volume=math.pi*r*r*h
  print('Volume of cylinder: ',volume)
def cone():
  r=int(input('Enter radius: '))
  h=int(input('Enter height: '))
  volume=(1/3)*math.pi*r*r*h
  print('Volume of cone: ',volume)
choice=input("Enter 1 for area calculations, 2 for volume calculations: ")
if choice=='1':
  print("Area Calculations")
  switch={
      '1':ar_circle,
      '2':ar_rect,
      '3':ar_tri,
      '4':ar_sq,
      '5':ar_para
  }
  ch=input("Enter 1 for circle, 2 for rectangle, 3 for triangle, 4 for square, 5 for parallelogram: ")
  if ch in switch:
    switch[ch]()
  else:
    print("Invalid Choice")

elif choice=='2':
  print("Volume Calculation: ")
  switch={
      '1':cube,
      '2':cuboid,
      '3':sphere,
      '4':cylinder,
      '5':cone }
  ch=input("Enter 1 for cube, 2 for cuboid, 3 for sphere, 4 for cylinder, 5 for cone: ")
  if ch in switch:
      switch[ch]()
  else:
    print("Invalid Choice")

"""## Problem 4: Primitive Data Types and Basic Operations.

Write a Python program to explore **primitive data types in Python**, understand their **memory size**, and perform **basic operations and type conversions**.

Primitive data types include:

- Integer (`int`)
- Float (`float`)
- Complex (`complex`)
- Boolean (`bool`)
- String (`str`)

---

### Part 1: Variable Creation

Create variables of the following primitive data types and assign suitable values.

| Data Type | Example Value |
|-----------|---------------|
| Integer | 25 |
| Float | 3.14 |
| Complex | 3 + 4j |
| Boolean | True |
| String | "Python Programming" |

Display the **value and data type** of each variable using the `type()` function.

Example output:

```
Value: 25  
Type: <class 'int'>
```

---

### Part 2: Memory Size of Data

Display the **memory size** of each variable using the `sys.getsizeof()` function.

Example:

```python
import sys
print(sys.getsizeof(a))
```

Print the size in **bytes** for each data type.

---

Display the **result and resulting data type**.

---

### Part 3: Exploring Complex Numbers

For a complex number variable, display the following properties:

- Real part using `.real`
- Imaginary part using `.imag`
- Magnitude using `abs()`

Example:

```
z = 3 + 4j
print(z.real)
print(z.imag)
print(abs(z))
```

---

### Part 4: Boolean Operations

Create two boolean variables and perform the following **logical operations**:

- AND (`and`)
- OR (`or`)
- NOT (`not`)

Example:

```
True and False
True or False
not True
```

### Part 5: Type Conversion

Perform the following **type conversions** and display the results:

- Integer → Float
- Float → Integer
- Integer → String
- String → Integer
- Boolean → Integer
- Integer → Complex

Example:

```
a = 10
z = complex(a)
print(z)
```
"""

import sys
inte=25
print("Value:",inte)
print("Type:", type(inte))
print("Size:",sys.getsizeof(inte))
floatt=3.14
print("Value:",floatt)
print("Type:",type(floatt))
print("Size:",sys.getsizeof(floatt))
complexx=3+4j
print("Value:",complexx)
print("Type:",type(complexx))
print("Size:",sys.getsizeof(complexx))
booll=True
print("Value:",booll)
print("Type:",type(booll))
print("Size:",sys.getsizeof(booll))
stringg="Python Programming"
print("Value:",stringg)
print("Type:",type(stringg))
print("Size:",sys.getsizeof(stringg))
z = 4 + 3j
print("Real: ",z.real)
print("Imaginary: ",z.imag)
print("Magnitude:", abs(z))
print("And Operation: ",True and False)
print("Or Operation: ",True or False)
print("Not operation: ",not True)
#Integer → Float
print("int to float",float(inte))
#Float → Integer
print("float to int",int(floatt))
#Integer → String
print("int to string",str(inte))
#String → Integer
stringg="10"
print("string to int",int(stringg))
#Boolean → Integer
a=int(booll)
print("Bool to int",a)
#Integer → Complex
print("Int to complex",complex(inte))

"""## Problem 5: Swap Two Numbers Without Temporary Variable

Write a program to swap two numbers **without using a third variable** using XOR.

"""

a=int(input('Enter number: '))
b=int(input('Enter number: '))
print('Before swapping :   a: ',a,'b: ',b)
a=a^b
b=a^b
a=a^b
print('After swapping:     a: ', a, 'b: ',b)

"""## Problem 6: Generate All Subsets Using Bit Masking

Given a set of elements, generate **all possible subsets using bit masking**.


Hint: Use numbers from:


$ 0 → 2^n - 1 $


to represent subsets.
"""

s=[]
n=int(input('Enter no. of elements: '))
for i in range(n):
  i=int(input('Enter element: '))
  s.append(i)
s=set(s)
print(s)
s=list(s)
def generate_subsets(arr):
    n = len(arr)
    subsets = []
    for mask in range(2**n):
        subset = []
        for i in range(n):
            if mask & (1 << i):   #checking if i-th bit is set
                subset.append(s[i])
        subsets.append(subset)
    return subsets
result = generate_subsets(s)
for subset in result:
    print(subset)

"""## Problem: Password Strength Checker

Write a Python program to check whether a given password is **strong or not** based on the following conditions.

### Password Requirements

A valid password should satisfy the following criteria:

1. The password must contain **at least 8 characters**.
2. The password must contain **at least one uppercase letter** (`A–Z`).
3. The password must contain **at least one lowercase letter** (`a–z`).
4. The password must contain **at least one digit** (`0–9`).
5. The password must contain **at least one special character** from the following set:

\[
! \ @ \ \# \ \$ \ \% \ \^ \ \& \ *
\]

### Task

Write a Python program that:

1. Takes a **password as input from the user**.
2. Checks whether the password satisfies the above conditions.
3. Based on the number of conditions satisfied, classify the password as:

| Conditions Satisfied | Password Strength |
|---------------------|------------------|
| 1–2 conditions | Weak |
| 3–4 conditions | Moderate |
| All 5 conditions | Strong |

### Example

**Input**

```
Enter Password: P@ss1234
```

**Output**

```
Password Strength: Strong
```
"""

password=input('Enter password: ')
count=0
#length
if len(password)>=8:
  count+=1
#upper
upper=False
for ch in password:
  if ch.isupper:
    upper=True
    break
if upper==True:
  count+=1
#lower
lower=False
for ch in password:
  if ch.islower():
    lower=True
    break
if lower==True:
  count+=1
#digit
digit=False
for ch in password:
  if ch.isdigit():
    digit=True
    break
if digit==True:
  count+=1
#Special
special="!@#$%^&*"
specials=False
for ch in password:
  if ch in special:
    specials=True
    break
if specials==True:
  count+=1
if count<=2:
  print("Password Strngth: Weak")
elif count<=4:
  print("Password Strngth: Moderate")
elif count==5:
  print("Password Strngth: Strong")

"""## Problem 7: Triangle Validation and Classification

A triangle is formed by three sides. However, not every set of three numbers can form a valid triangle.  
The **Triangle Inequality Theorem** states that the sum of the lengths of any two sides of a triangle must be **greater than the third side**.

Mathematically,

\[
a + b > c
\]

\[
a + c > b
\]

\[
b + c > a
\]

where \(a\), \(b\), and \(c\) represent the three sides of the triangle.

---

### Task

Write a Python program that performs the following steps:

1. Take the **three side lengths** of a triangle as input from the user.
2. Check whether the given sides satisfy the **triangle inequality condition**.
3. If the triangle is **not valid**, display an appropriate message.
4. If the triangle is **valid**, determine the type of triangle.

---

### Triangle Classification

If the triangle is valid, classify it based on the side lengths:

| Triangle Type | Condition |
|---------------|-----------|
| Equilateral Triangle | All three sides are equal |
| Isosceles Triangle | Any two sides are equal |
| Scalene Triangle | All three sides are different |

---

### Example 1

**Input**

```
Enter side a: 5
Enter side b: 5
Enter side c: 5
```

**Output**

```
Valid Triangle
Type: Equilateral Triangle
```

---

### Example 2

**Input**

```
Enter side a: 4
Enter side b: 4
Enter side c: 6
```

**Output**

```
Valid Triangle
Type: Isosceles Triangle
```

---

### Example 3

**Input**

```
Enter side a: 2
Enter side b: 3
Enter side c: 10
```

**Output**

```
Not a valid triangle
```


"""

a=int(input('Enter side a: '))
b=int(input('Enter side b: '))
c=int(input('Enter side c: '))
flag=0
if a+b>c and a+c>b and b+c>a:
  flag=1
else:
  flag=0
if flag==1:
  print("Valid Triangle")
  if a==b and b==c:
    print("Type: Equilateral Triangle")
  elif a==b or b==c or a==c:
    print("Type: Isosceles Triangle")
  else:
    print("Type: Scalene Triangle")
elif flag==0:
  print("Not a valid Triangle")